# Generated by Django 5.0.4 on 2024-04-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(blank=True, max_length=50)),
                ('Cuantas_Gb_Ram', models.TextField(blank=True, max_length=5000)),
                ('Tipo_pantalla', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('Nombre_Procesador', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
    ]
