# Generated by Django 5.0.4 on 2024-04-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='Cuantas_Gb_Ram',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='celular',
            name='Modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='celular',
            name='Nombre_Procesador',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='celular',
            name='Tipo_pantalla',
            field=models.TextField(),
        ),
    ]
